name: bandgap
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - rdkit
  - pip:
    - lightgbm==4.3.0
    - optuna==3.6.0
    - shap==0.45.0
    - mlflow==2.13.0
    - scikit-learn==1.4.2
    - matminer
    - pymatgen
    - pandas
    - numpy
    - matplotlib
    - pytest
    - jupyter